# Generated by Django 4.0.3 on 2022-03-21 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('isbn', models.CharField(max_length=255)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='bokksapp.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.FloatField()),
                ('payment_type', models.CharField(max_length=255)),
                ('shipping_type', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('books', models.ManyToManyField(to='bokksapp.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokksapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_path', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bokksapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(to='bokksapp.genres'),
        ),

        migrations.RunSQL(
            'ALTER TABLE bokksapp_users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_users ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),

        migrations.RunSQL(
            'ALTER TABLE bokksapp_books ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_books ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),

        migrations.RunSQL(
            'ALTER TABLE bokksapp_genres ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_genres ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),

        migrations.RunSQL(
            'ALTER TABLE bokksapp_authors ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_authors ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),

        migrations.RunSQL(
            'ALTER TABLE bokksapp_events ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_events ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_orders ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
        migrations.RunSQL(
            'ALTER TABLE bokksapp_orders ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;'
        ),
    ]
